language: node_js

node_js:
  - 10

branches:
  only:

before_install:

install:
- yarn install

before_script:

script:
  - yarn build
  - yarn semantic-release
  # - yarn test
  # - yarn build && git add . && git commit -m 'build' &&  git push origin feature/travis.build
  # - rm a.txt && touch a.txt && git add . && git commit -m 'test' &&  git push origin feature/travis.build